dataset:
  data_folder: "data"
  batch_size: 2

model:
  n_blocks: 4
  c_latent: 4
  d_embd: 8
  n_head: 2
  d_time_embd: 8
  d_cond_embd: 8
  patch_size: 2

train:
  n_epochs: 100000
  learning_rate: 0.005
  weight_decay: 0.01
  