dataset:
  data_folder: "data"
  batch_size: 256

model:
  n_blocks: 12
  c_latent: 4
  d_embd: 768
  n_head: 12
  d_time_embd: 256
  patch_size: 2

train:
  n_epochs: 1
  learning_rate: 0.01
  weight_decay: 0.01
  